### ISSUE TITLE
Can't start a process

### ISSUE THREAD

**Issue by lantonov** [lucasart/zinc#27]
```
C:\Rockstar>python zinc.py
Traceback (most recent call last):
  File "zinc.py", line 409, in <module>
    run_pool([Engines[0], e], fens, tablebases, TimeControls, Concurrency, PgnOut)
  File "zinc.py", line 310, in run_pool
    p.start()
  File "C:\WinPython\python-3.6.1.amd64\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\WinPython\python-3.6.1.amd64\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\WinPython\python-3.6.1.amd64\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\WinPython\python-3.6.1.amd64\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\WinPython\python-3.6.1.amd64\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects

C:\Rockstar>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\WinPython\python-3.6.1.amd64\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\WinPython\python-3.6.1.amd64\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
```
Too obscure for me

**Comment by lantonov** [comment]
Using package `multiprocess` instead of `multiprocessing` appears to work but now the following appears
```
Process Process-1:
Traceback (most recent call last):
  File "D:\archive\WinPython\python-3.5.4\python-3.5.4\lib\site-packages\multipr
ocess\process.py", line 249, in _bootstrap
    self.run()
  File "D:\archive\WinPython\python-3.5.4\python-3.5.4\lib\site-packages\multipr
ocess\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "zinc.py", line 365, in play_games
    TimeControls, tablebases, pgnOut, job.round)
  File "D:\archive\rockstar\RWO\zinc.py", line 195, in play_game
    wdl = tablebases.probe_wdl(board)
  File "D:\archive\WinPython\python-3.5.4\python-3.5.4\lib\site-packages\chess\s
yzygy.py", line 1672, in probe_wdl
    raise KeyError("syzygy tables do not contain positions with castling rights:
 {0}".format(board.fen()))
KeyError: 'syzygy tables do not contain positions with castling rights: rn1qkbnr
/ppp1pppp/8/3p1b2/2P5/1P6/P2PPPPP/RNBQKBNR w KQkq - 0 1'

```
The problem is in lines 194-197
```python
        if board.halfmove_clock == 0:
            wdl = tablebases.probe_wdl(board)
            if wdl is not None:
                break
```
Commenting these out makes the program working (without TB though)
